[package]
name = "oxidalloc"
version = "0.2.0"
edition = "2024"

[features]
loom = []

[dependencies]
rustix = { version = "1.1.3", features = ["mm"] }
libc = "0.2.180"

[dev-dependencies]
loom = "0.7"

[lib]
name = "oxidalloc"
crate-type = ["cdylib", "rlib"]

[profile.dev]
opt-level = 3
debug = true
debug-assertions = true
overflow-checks = true
panic = "abort"
incremental = false
codegen-units = 1
lto = "fat"
strip = "none"

[profile.release]
opt-level = 3
debug = true
panic = "abort"
overflow-checks = true
lto = "fat"
codegen-units = 1

[profile.dev-opt]
inherits = "dev"
opt-level = 2
debug = true
debug-assertions = true
overflow-checks = true
panic = "abort"
codegen-units = 1
